* Introduction

This configuration file contains my Gnus configuration, for accessing mail at
Gmail.  Since my Gmail account is set up to get mail from the rest of my email
accounts, and send as them too, I only need to have this one account set up.

* Implementation
** Package Installation

You do need gnus.  However, I'm pretty sure that it comes preinstalled on Emacs.
Also, BBDB, which is not installed by default.

#+begin_src emacs-lisp :tangle yes
(stemacs-require '(bbdb))
#+end_src

** Configuration

This is from the [[http://www.emacswiki.org/emacs/GnusGmail][Emacs Wiki]]
article on Gnus.  These are the IMAP and SMTP settings necessary.

#+name: init
#+begin_src emacs-lisp
(setq gnus-select-method
      '(nnimap "gmail"
	       (nnimap-address "imap.gmail.com")
	       (nnimap-server-port 993)
	       (nnimap-stream ssl)))

(setq message-send-mail-function 'smtpmail-send-it
      smtpmail-starttls-credentials '(("smtp.gmail.com" 587 nil nil))
      smtpmail-auth-credentials '(("smtp.gmail.com" 587
				   "brenns10@gmail.com" nil))
      smtpmail-default-smtp-server "smtp.gmail.com"
      smtpmail-smtp-server "smtp.gmail.com"
      smtpmail-smtp-service 587
      gnus-ignored-newsgroups "^to\\.\\|^[0-9. ]+\\( \\|$\\)\\|^[\"]\"[#'()]")
#+end_src

Also required is a .authinfo file with SMTP and IMAP server entries.  It
prevents you from having to specify the password.  This file should definitely
have 600 permissions.  The file should look something like this:

#+BEGIN_EXAMPLE
machine imap.gmail.com login [email] password [password] port 993
machine smtp.gmail.com login [email] password [password] port 587
#+END_EXAMPLE

The following settings set my From address accordingly (although I may want to
mail from different addresses).

#+begin_src emacs-lisp :tangle yes
(setq user-full-name "Stephen Brennan"
      user-mail-address "brenns10@gmail.com")
#+end_src

This code is cut and pasted from [[https://eschulte.github.io/emacs24-starter-kit/starter-kit-gnus.html][Starter Kit Gnus]].  It makes the summary view
look much more like an email list.

#+begin_src emacs-lisp :tangle yes
; http://groups.google.com/group/gnu.emacs.gnus/browse_thread/thread/a673a74356e7141f
(when window-system
  (setq gnus-sum-thread-tree-indent "  ")
  (setq gnus-sum-thread-tree-root "") ;; "● ")
  (setq gnus-sum-thread-tree-false-root "") ;; "◯ ")
  (setq gnus-sum-thread-tree-single-indent "") ;; "◎ ")
  (setq gnus-sum-thread-tree-vertical        "│")
  (setq gnus-sum-thread-tree-leaf-with-other "├─► ")
  (setq gnus-sum-thread-tree-single-leaf     "╰─► "))
(setq gnus-summary-line-format
      (concat
       "%0{%U%R%z%}"
       "%3{│%}" "%1{%d%}" "%3{│%}" ;; date
       "  "
       "%4{%-20,20f%}"               ;; name
       "  "
       "%3{│%}"
       " "
       "%1{%B%}"
       "%s\n"))
(setq gnus-summary-display-arrow t)
#+end_src

For contacts, I'm using BBDB.  This seems to work for me.  I downloaded my
Google Contacts in VCF, and used bbdb-vcard to import them.

#+begin_src emacs-lisp :tangle yes
;;; bbdb
(require 'bbdb)
(bbdb-initialize 'gnus 'message)
(setq
 bbdb-file "~/.bbdb"
 bbdb-offer-save 'auto
 bbdb-notice-auto-save-file t
 bbdb-expand-mail-aliases t
 bbdb-canonicalize-redundant-nets-p t
 bbdb-always-add-addresses t
 bbdb-complete-name-allow-cycling t
 )
#+end_src
