* Introduction

This configuration file contains my Gnus configuration, for accessing mail at
Gmail.  Since my Gmail account is set up to get mail from the rest of my email
accounts, and send as them too, I only need to have this one account set up.

* Implementation
** Package Installation

You do need gnus.  However, I'm pretty sure that it comes preinstalled on Emacs.
Also, BBDB, which is not installed by default.

#+begin_src emacs-lisp :tangle yes
(stemacs-require '(bbdb))
#+end_src

** Configuration

This is from the [[http://www.emacswiki.org/emacs/GnusGmail][Emacs Wiki]] article on Gnus.  These are the IMAP and SMTP
settings necessary.

#+name: init
#+begin_src emacs-lisp
(setq gnus-select-method
      '(nnimap "gmail"
	       (nnimap-address "imap.gmail.com")
	       (nnimap-server-port 993)
	       (nnimap-stream ssl)))

(setq message-send-mail-function 'smtpmail-send-it
      smtpmail-starttls-credentials '(("smtp.gmail.com" 587 nil nil))
      smtpmail-auth-credentials '(("smtp.gmail.com" 587
				   "brenns10@gmail.com" nil))
      smtpmail-default-smtp-server "smtp.gmail.com"
      smtpmail-smtp-server "smtp.gmail.com"
      smtpmail-smtp-service 587
      gnus-ignored-newsgroups "^to\\.\\|^[0-9. ]+\\( \\|$\\)\\|^[\"]\"[#'()]")
#+end_src

Also required is a .authinfo file with SMTP and IMAP server entries.  It
prevents you from having to specify the password.  This file should definitely
have 600 permissions.  The file should look something like this:

#+BEGIN_EXAMPLE
machine imap.gmail.com login [email] password [password] port 993
machine smtp.gmail.com login [email] password [password] port 587
#+END_EXAMPLE

The following settings set my From address accordingly (although I may want to
mail from different addresses).

#+begin_src emacs-lisp :tangle yes
(setq user-full-name "Stephen Brennan"
      user-mail-address "brenns10@gmail.com")
#+end_src

** Customization

This code is cut and pasted from [[https://eschulte.github.io/emacs24-starter-kit/starter-kit-gnus.html][Starter Kit Gnus]].  It makes the summary view
look much more like an email list.

#+begin_src emacs-lisp :tangle yes
; http://groups.google.com/group/gnu.emacs.gnus/browse_thread/thread/a673a74356e7141f
(when window-system
  (setq gnus-sum-thread-tree-indent "  ")
  (setq gnus-sum-thread-tree-root "") ;; "● ")
  (setq gnus-sum-thread-tree-false-root "") ;; "◯ ")
  (setq gnus-sum-thread-tree-single-indent "") ;; "◎ ")
  (setq gnus-sum-thread-tree-vertical        "│")
  (setq gnus-sum-thread-tree-leaf-with-other "├─► ")
  (setq gnus-sum-thread-tree-single-leaf     "╰─► "))
(setq gnus-summary-line-format
      (concat
       "%0{%U%R%z%}"
       "%3{│%}" "%1{%d%}" "%3{│%}" ;; date
       "  "
       "%4{%-20,20f%}"               ;; name
       "  "
       "%3{│%}"
       " "
       "%1{%B%}"
       "%s\n"))
(setq gnus-summary-display-arrow t)
#+end_src

This sets Gnus to display all messages in any group, and make the Inbox always
visible.

#+begin_src emacs-lisp :tangle yes
(setq gnus-parameters
  '((".*"
     (display . all)
     (gnus-use-scoring nil))))
(setq gnus-permanently-visible-groups "INBOX")
#+end_src

Gnus takes an obnoxiously long time to load, since it has to get a listing from
every single folder before it loads.  I only want my Inbox -- none of the
folders matter to me, so long as I can read, reply, and archive.  So, I set the
inbox to level 1, and everything else to level 7, and then set Gnus to only read
from level 1 at startup.

#+begin_src emacs-lisp :tangle yes
(setq gnus-activate-level 1)
#+end_src

This has Gnus display the newest emails first.

#+begin_src emacs-lisp :tangle yes
(setq gnus-thread-sort-functions
  '(gnus-thread-sort-by-most-recent-number))
#+end_src

These commands give me easier access to PGP encryption services.

#+begin_src emacs-lisp :tangle yes
(setq mm-verify-option 'always)
(setq mm-decrypt-option 'always)
(setq mm-encrypt-option 'guided)
(setq gnus-buttonized-mime-types '("multipart/signed"))
#+end_src

Use the topic view in Group mode.

#+begin_src emacs-lisp :tangle yes
(add-hook 'gnus-group-mode-hook 'gnus-topic-mode)
#+end_src

This will automatically quit Gnus non-interactively when Emacs exits, so I don't
need to worry about correctly exiting it myself.

#+begin_src emacs-lisp :tangle yes
(setq gnus-interactive-exit nil)
(add-hook 'kill-emacs-hook (lambda ()
                            (when (boundp 'gnus-group-exit)
                                 (gnus-group-exit))))
#+end_src

Don't let Gnus take the entire window **every time I open something**.

#+begin_src emacs-lisp :tangle yes
(setq gnus-use-full-window nil)
#+end_src

Some keys and mouse gestures that make mail navigation easier:
- Use "n" and "p" for navigation, without control button.
- Create a shortcut "v x" that will close the open article buffer.
- Use middle click on article buffer to close it.  Since there is already
  functionality to middle click on message and view it (in Summary view), this
  makes mouse navigation nice using middle click.

#+begin_src emacs-lisp :tangle yes
(defun stemacs-switch-close ()
  "Switch window and close it."
  (interactive)
  (progn
    (other-window 1)
    (delete-window)))

(defun stemacs-mouse-close (event)
  "Switch to the clicked window and close it."
  (interactive "e")
  (let ((w (posn-window (event-start event))))
    (if (window-valid-p w)
      (delete-window (select-window w))
      nil)))

(add-hook 'gnus-summary-mode-hook
  (lambda ()
    (progn
      (define-key gnus-summary-mode-map (kbd "v x") 'stemacs-switch-close)
      (define-key gnus-summary-mode-map (kbd "n") 'next-line)
      (define-key gnus-summary-mode-map (kbd "p") 'previous-line))))
(add-hook 'gnus-article-mode-hook
  (lambda ()
    (define-key gnus-article-mode-map [down-mouse-2] 'stemacs-mouse-close)))
#+end_src

For contacts, I'm using BBDB.  This seems to work for me.  I downloaded my
Google Contacts in VCF, and used bbdb-vcard to import them.

#+begin_src emacs-lisp :tangle yes
;;; bbdb
(require 'bbdb)
(bbdb-initialize 'gnus 'message)
(setq
 bbdb-file "~/.bbdb"
 bbdb-offer-save 'auto
 bbdb-notice-auto-save-file t
 bbdb-expand-mail-aliases t
 bbdb-canonicalize-redundant-nets-p t
 bbdb-always-add-addresses t
 bbdb-complete-name-allow-cycling t
 )
#+end_src
