* Introduction

This is the root of my emacs configuration.  I'm using Babel to embed ELisp into
this org-mode file, and it is loaded by my init.el.  The init.el only contains
code to load this file.

I'm trying to make my Emacs configuration modular.  The idea is that each module
will have a list of required packages, along with configuration code.  The
modules will install their packages if not already there, and then run their
code.

* Implementation
** Package Installation

This code initializes the package archives on startup.

#+begin_src emacs-lisp :tangle yes
(require 'package)
(add-to-list 'package-archives '("melpa" . "http://melpa.milkbox.net/packages/") t)
(package-initialize)

; fetch the list of packages available
(or (file-exists-p package-user-dir)
    (package-refresh-contents))
#+end_src

A function that will allow modules to require a package, and install it if it
isn't installed.

#+begin_src emacs-lisp :tangle yes
(defun stemacs-require (package-list)
  (dolist (package package-list)
    (unless (package-installed-p package)
      (package-install package))))
#+end_src

A shortcut for the code below to load files.

#+begin_src emacs-lisp :tangle yes
(defun stemacs-load (filename)
  (org-babel-load-file (expand-file-name filename stemacs-dir)))
#+end_src

** Modules

The editor module stores my basic editor preferences, that don't pertain to a
particular mode or anything else.

#+begin_src emacs-lisp :tangle yes
(stemacs-load "editor.org")
#+end_src

Yasnippet

#+begin_src emacs-lisp :tangle yes
(stemacs-load "yas.org")
#+end_src

Helm

#+begin_src emacs-lisp :tangle yes
(stemacs-load "helm.org")
#+end_src

Autocomplete

#+begin_src emacs-lisp :tangle yes
(stemacs-load "autocomplete.org")
#+end_src

Python

#+begin_src emacs-lisp :tangle yes
(stemacs-load "python.org")
#+end_src

LaTeX

#+begin_src emacs-lisp :tangle yes
(stemacs-load "latex.org")
#+end_src

Markdown

#+begin_src emacs-lisp :tangle yes
(stemacs-load "markdown.org")
#+end_src

KMail email settings

#+begin_src emacs-lisp :tangle yes
(stemacs-load "kmail.org")
#+end_src

Gnus email

#+begin_src emacs-lisp :tangle yes
(stemacs-load "gnus.org")
#+end_src

C coding

#+begin_src emacs-lisp :tangle yes
(stemacs-load "c.org")

#+end_src
