* Introduction

This is the root of my emacs configuration.  I'm using Babel to embed ELisp into
this org-mode file, and it is loaded by my init.el.  The init.el only contains
code to load this file.

I'm trying to make my Emacs configuration modular.  The idea is that each module
will have a list of required packages, along with configuration code.  The
modules will install their packages if not already there, and then run their code.

* Implementation
** Package Installation

This code initializes the package archives on startup, and defines a function to
install a list of packages.  The function should be used by each of the modules
to require a package.

#+name: package-installation
#+begin_src emacs-lisp
  (require 'package)
  (add-to-list 'package-archives '("melpa" . "http://melpa.milkbox.net/packages/") t)
  (package-initialize)

  ; fetch the list of packages available
  (or (file-exists-p package-user-dir)
    (package-refresh-contents))

  (defun stemacs-require (package-list)
    (dolist (package package-list)
      (unless (package-installed-p package)
        (package-install package))))
#+end_src

** Modules

The editor module stores my basic editor settings, that don't pertain to a
particular mode or anything else.

#+name: init
#+begin_src emacs-lisp
(org-babel-load-file (expand-file-name "editor.org" stemacs-dir))
#+end_src

Yasnippet

#+name: init
#+begin_src emacs-lisp
(org-babel-load-file (expand-file-name "yas.org" stemacs-dir))
#+end_src

Helm

#+name: init
#+begin_src emacs-lisp
(org-babel-load-file (expand-file-name "helm.org" stemacs-dir))
#+end_src

Autocomplete

#+name: init
#+begin_src emacs-lisp
(org-babel-load-file (expand-file-name "autocomplete.org" stemacs-dir))
#+end_src

Python

#+name: init
#+begin_src emacs-lisp
(org-babel-load-file (expand-file-name "python.org" stemacs-dir))
#+end_src

LaTeX

#+begin_src emacs-lisp :tangle yes
(org-babel-load-file (expand-file-name "latex.org" stemacs-dir))
#+end_src

Markdown

#+begin_src emacs-lisp :tangle yes
(org-babel-load-file (expand-file-name "markdown.org" stemacs-dir))
#+end_src

KMail temp files.  The proper line length is 78 characters.

#+begin_src emacs-lisp :tangle yes
(org-babel-load-file (expand-file-name "kmail.org" stemacs-dir))
#+end_src
